## Import libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Import the dataset

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head(5)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
x = df.iloc[:, :-1].values

In [5]:
y = df.iloc[:, -1].values

## Split the dataset into training and test sets

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 0)

## Feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()

In [10]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Training the model

In [11]:
from sklearn.svm import SVC

In [26]:
classifier = SVC(kernel='linear', random_state=0)

In [27]:
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

## Predicting a new result

In [28]:
print(classifier.predict(sc.transform([[30, 87000]])))

[0]


## Predicting the test results

In [29]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


## Confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[66  2]
 [ 8 24]]


## Accuracy score

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9

In [32]:
classifier.decision_function(x_test)

array([-1.56813388, -1.34026533, -1.11239633, -1.79344243, -1.81648557,
       -3.93131327, -3.43717081,  0.98963005, -4.00812263, -0.10874962,
       -2.63834952, -2.78684826, -1.35818756, -0.42110888, -3.18369822,
       -0.40574663, -0.73858903, -3.37060187,  3.61140155, -2.60506552,
       -1.90097628,  2.73577091, -0.83588153,  1.63739169, -4.34096503,
        2.96876035, -1.88561403, -1.92401894, -1.16104258, -1.27881729,
       -2.96863101, -0.68226189,  1.95743183, -1.4145147 , -3.33731786,
       -4.45873974, -3.00703592, -2.17237063, -2.90206299,  0.01158554,
       -2.01619054, -0.80771796, -2.12884482, -2.66139265,  1.19957637,
       -2.86109763, -0.65409832,  2.00863854, -3.80841766,  1.41976402,
        3.70357315, -2.67931488, -1.61934058, -0.14459362,  3.06349194,
       -0.73602904, -1.83952823, -2.40023918, -0.21372301, -4.56627358,
       -3.19394003,  1.92670781, -3.624074  , -0.27773058, -5.03225248,
        3.08141417, -2.4642472 , -2.86109763, -1.10727589, -0.14